[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.5",
    "djangorestframework>=3.17.1",
    "psycopg2-binary>=2.9.12",
]

[tool.tomlscript] 
# runserver 
dev = "uv run manage.py runserver" 
# manage.py 
manage = "uv run manage.py" 
# makemigrations and migrate 
migrate = "uv run manage.py makemigrations && uv run manage.py migrate" 
# startapp 
startapp = "uv run manage.py startapp"
