[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "bs4>=0.0.2",
  "celery>=5.6.3",
  "chromadb>=1.5.9",
  "django>=6.0.5",
  "django-cors-headers>=4.9.0",
  "djangorestframework>=3.17.1",
  "djangorestframework-simplejwt>=5.5.1",
  "gitpython>=3.1.49",
  "langchain>=1.2.17",
  "langchain-groq>=1.1.2",
  "langchain-text-splitters>=1.1.2",
  "lxml>=6.1.0",
  "passlib[argon2]>=1.7.4",
  "psycopg2-binary>=2.9.12",
  "python-dotenv>=1.2.2",
  "redis>=7.4.0",
]

[tool.tomlscript] 
# runserver 
dev = "uv run manage.py runserver" 
# manage.py 
manage = "uv run manage.py" 
# makemigrations and migrate 
migrate = "uv run manage.py makemigrations && uv run manage.py migrate" 
# startapp 
startapp = "uv run manage.py startapp"
