# Generated by Django 6.0.5 on 2026-05-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("collection_name", models.CharField(max_length=255)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
